spack:
  specs:
    - psakievich
    - tmux
  view:
    base:
      root: ${HOME}/myconfig
      projections:
        openssl: '{name}/{version}'
  concretizer:
    targets:
      granularity: generic
